# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63861e2e0a09ef3f1cc992c2bb82bd8eb90472b2c936c08e94e184512f1b17c5cd8d810aa57c9a3ddd303ef723300b1473ead814971e6a3cd0bbe8fbb0ebe86d

test:
  secret_key_base: f02005aba2d22a1ce92edd5d6bf809256fe597c4a0b094af967d1f3347cefed52c13a07b73163489ec500d49e1f3d63009707e8656a724817298ad3e3810b83c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
